[package]
name = "odserver"
version = "0.1.0"
authors = ["Evgeniy Polyakov <zbr@ioremap.net>"]

[dependencies]
clap = "2"
futures = "0.1.14"
hyper = "0.11.2"
image = "*"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tensorflow = "*"
